### ISSUE TITLE
Cannot register 2 metrics with the same name: /tensorflow/api/keras/optimizers

### ISSUE THREAD

**Issue by EricCousineau-TRI** [google-research/ibc#1]
Just tried running tests on Ubuntu 20.04, CPython 3.8.10, but get the following error:
```
$ cd ibc/..
$ ./ibc/run_tests.sh
...
PYTHONPATH=:{parent}/ibc/.. python3 {parent}/ibc/ibc/agents/mcmc_test.py --alsologtostderr
...
2021-11-08 16:03:33.113843: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-11-08 16:03:33.113875: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-11-08 16:03:34.161325: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/api/keras/optimizers
...
tensorflow.python.framework.errors_impl.AlreadyExistsError: Another metric with the same name already exists.
ERROR: 'PYTHONPATH=:{parent}/ibc/.. python3 {parent}/ibc/ibc/agents/mcmc_test.py --alsologtostderr' failed!
```

Full stack trace: https://gist.github.com/EricCousineau-TRI/ac6e9943606e6b9f7e335882f7caa350

~Not sure if it's b/c of CUDA error.~
~I have stock Ubuntu CUDA 10.1 on my machine, so will try out NVidia-installed CUDA 11.0.~
See below.

Also happens when trying to run training script, `./ibc/ibc/configs/pushing_states/run_mlp_ebm.sh`

**Comment by EricCousineau-TRI** [comment]
Installed CUDA 11.5, cuDNN 8.3 from NVidia repos; no longer seeing error about loading `cudart.so` etc., but this error still occurs.
Updated Gist to

**Comment by peteflorence** [comment]
Hi Eric,
It looks like this issue can be reproducible just from:

```
python
>> import tensorflow_probability as tfp
```

Can you verify that?

Also, is it possible for you to install exactly the versions that we tested it with?  Note that Tensorflow version is 2.6.0, and it only wants CUDA 11.2 and cuDNN 8.1.0.  (You can see that [here](https://www.tensorflow.org/install/gpu), but there's nothing really to see there other than yes CUDA 11.2)
However, your latest stack trace seems to not have to do with cuda, so I'm not sure about that one.

**Comment by peteflorence** [comment]
Hi Eric, it looks like you have both `tfp-nightly` and `tensorflow-probability` installed, which according to the TFP folks is "extra not recommended"

Can you: `pip uninstall tfp-nightly`?

**Comment by EricCousineau-TRI** [comment]
Howdy Pete! Haha, quite understood. I think that probably came from `tf-agents-nightly`?

I was not able to repro the error with `python3 -c 'import tensorflow_probability'`.
However, I could repro with `python3 -c 'import tf_agents'`.

When uninstalling `tfp-nightly`, I get new error :sweat_smile: 

```
$ python3 -c 'import tf_agents'
...
  File "{venv}/lib/python3.8/site-packages/tf_agents/typing/types.py", line 50, in <module>
    Distribution = tfp.distributions.Distribution
AttributeError: module 'tensorflow_probability' has no attribute 'distributions'
```

Lemme try a few more configs.

**Comment by EricCousineau-TRI** [comment]
I get the same error even with this min env:
```
$ python3 -m venv .
$ source ./bin/activate
$ pip install -U pip wheel
$ pip install \
  tensorflow==2.6.0 \
  tf-agents==0.11.0rc0
$ python3 -c 'import tf_agents'
```

**Comment by EricCousineau-TRI** [comment]
I think I found one solution, submitted as #3 - thanks!!!

**Comment by peteflorence** [comment]
Thank you Eric for finding and posting the fix! Much appreciated.

I will test this out on my side as well.  I had done a bunch of dependency testing in a clean Docker container... I was hoping :crossed_fingers: all the dependencies would have just worked out of the box!  Oh well :)

If anybody else sees this and either (a) didn't have this problem, or (b) did have this problem and https://github.com/google-research/ibc/pull/3 fixed it, it would be helpful to know, thanks!

**Comment by yenchenlin** [comment]
I can confirm that #3 fixes it.

People have found this issue [here](https://github.com/tensorflow/tensorflow/issues/51592#issuecomment-960363675) and [here](https://stackoverflow.com/questions/58012741/error-importing-tensorflow-alreadyexistserror-another-metric-with-the-same-nam/69830680#69830680) too.

**Comment by peteflorence** [comment]
Thanks @yenchenlin !

**Comment by peteflorence** [comment]
Thanks again @EricCousineau-TRI and @yenchenlin.  And thanks @ayzaan for merging this in!
