### ISSUE TITLE
Goal Tolerance Are Different for Different Methods

### ISSUE THREAD

**Issue by yenchenlin** [google-research/ibc#5]
Hi, I found that 
```
train_eval.goal_tolerance = 0.02
```
is set in [EBM's config](https://github.com/google-research/ibc/blob/03452d37cf6a9878969fbc2c982c633bfeefe504/ibc/configs/pushing_states/mlp_ebm.gin#L25) but not in [MSE's config](https://github.com/google-research/ibc/blob/03452d37cf6a9878969fbc2c982c633bfeefe504/ibc/configs/pushing_states/mlp_mse.gin).

The difference makes the evaluation to be more strict on MSE-based BC as the default `goal_tolerance=0.01` ([code](https://github.com/google-research/ibc/blob/03452d37cf6a9878969fbc2c982c633bfeefe504/environments/block_pushing/block_pushing.py#L178)).

Setting `train_eval.goal_tolerance = 0.01` for the EBM agent decreases its success rate from `1.0` to `[0.85, 0.95]` after training for 10k steps.

**Comment by yenchenlin** [comment]
Setting `train_eval.goal_tolerance = 0.01` for the EBM agent decreases its success rate from `1.0` to `[0.85, 0.95]` after training for 10k steps.

**Comment by peteflorence** [comment]
Thanks Yen-Chen. This only affects block push. I’m pretty sure the configs
we used for the paper results had them the same, but I’ll double check.
Also as we reported in the paper MSE should be able to solve the task to
~100% with certain hyperparams, same as EBM.

**Comment by peteflorence** [comment]
Yup confirmed that the paper results used 0.02.
Also, the pushings_pixels mse config in the open-source release also has the correct 0.02: https://github.com/google-research/ibc/blob/master/ibc/configs/pushing_pixels/pixel_mse_best.gin#L25
Looks like just the pushing_states that is missing it.  Thanks for the heads up!  Will get a PR out eventually to update it.
Please let me know if you find anything else.

**Comment by yenchenlin** [comment]
Got it, thanks for the quick reply!
